# Scrapping Quotes

So we will now scrapping the quotes from the website and storing it in a csv file. We will be using the requests library to get the HTML content of the webpage and BeautifulSoup to parse the HTML and extract the quotes.

## Step 1: Importing Libraries and Connecting to the Website

In [ ]:
# import the necessary libraries and make a request to the webpage and then parse the webpage using BeautifulSoup
import requests
from bs4 import BeautifulSoup
import pandas as pd
link = 'https://quotes.toscrape.com/'
res = requests.get(link)
soup = BeautifulSoup(res.text, 'html.parser')

## Step 2: Scarping Quotes

In [48]:
# Extracting the quotes from the webpage
quotes = []
for quote in soup.find_all('span', class_='text'):
    quotes.append(quote.text[1:-1])
    print(quote.text[1:-1])

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
It is our choices, Harry, that show what we truly are, far more than our abilities.
There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Try not to become a man of success. Rather become a man of value.
It is better to be hated for what you are than to be loved for what you are not.
I have not failed. I've just found 10,000 ways that won't work.
A woman is like a tea bag; you never know how strong it is until it's in hot water.
A day without sunshine is like, you know, night.

## Step 3: Scarping Author Names

In [49]:
# Extracting the Authors of the quotes
authors = []
for quote in soup.find_all('small', class_='author'):
    authors.append(quote.text)
    print(quote.text)

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin

##  Step 4: Scrapping Proflie Link

In [50]:
# Extracting the profile links of the authors
profile_link = []

for quote in soup.find_all('div', class_='quote'):
    link = quote.find('a').get('href')
    profile_link.append(link)
    print(link)

/author/Albert-Einstein
/author/J-K-Rowling
/author/Albert-Einstein
/author/Jane-Austen
/author/Marilyn-Monroe
/author/Albert-Einstein
/author/Andre-Gide
/author/Thomas-A-Edison
/author/Eleanor-Roosevelt
/author/Steve-Martin

##  Step 4: Scrapping Tags of the quotes

In [51]:
# Extracting the tags of the quotes
tags=[]
for quote in soup.find_all('div', class_='quote'):
    tag = quote.find_all('a', class_='tag')
    tags.append([t.text for t in tag])
    print([t.text for t in tag])

['change', 'deep-thoughts', 'thinking', 'world']
['abilities', 'choices']
['inspirational', 'life', 'live', 'miracle', 'miracles']
['aliteracy', 'books', 'classic', 'humor']
['be-yourself', 'inspirational']
['adulthood', 'success', 'value']
['life', 'love']
['edison', 'failure', 'inspirational', 'paraphrased']
['misattributed-eleanor-roosevelt']
['humor', 'obvious', 'simile']

This is how you can extract the quotes, authors, profile links and tags from the webpage.

## Step 5:Store the Data in the list

In [52]:
# Sore the data in a list of dictionaries
Data=[]
for i in range(len(quotes)):
    Data.append({
        'Quote': quotes[i],
        'Author': authors[i],
        'Profile Link': profile_link[i],
        'Tags': tags[i]
    })

In [53]:
Data

[{'Quote': 'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.',
  'Author': 'Albert Einstein',
  'Profile Link': '/author/Albert-Einstein',
  'Tags': ['change', 'deep-thoughts', 'thinking', 'world']},
 {'Quote': 'It is our choices, Harry, that show what we truly are, far more than our abilities.',
  'Author': 'J.K. Rowling',
  'Profile Link': '/author/J-K-Rowling',
  'Tags': ['abilities', 'choices']},
 {'Quote': 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.',
  'Author': 'Albert Einstein',
  'Profile Link': '/author/Albert-Einstein',
  'Tags': ['inspirational', 'life', 'live', 'miracle', 'miracles']},
 {'Quote': 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.',
  'Author': 'Jane Austen',
  'Profile Link': '/author/Jane-Austen',
  'Tags': ['aliteracy', 'books', 'classic', 'humor']},
 {'Quote': "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
  'Author': 'Marilyn Monroe',
  'Profile Link': '/author/Marilyn-Monroe',
  'Tags': ['be-yourself', 'inspirational']},
 {'Quote': 'Try not to become a man of success. Rather become a man of value.',
  'Author': 'Albert Einstein',
  'Profile Link': '/author/Albert-Einstein',
  'Tags': ['adulthood', 'success', 'value']},
 {'Quote': 'It is better to be hated for what you are than to be loved for what you are not.',
  'Author': 'André Gide',
  'Profile Link': '/author/Andre-Gide',
  'Tags': ['life', 'love']},
 {'Quote': "I have not failed. I've just found 10,000 ways that won't work.",
  'Author': 'Thomas A. Edison',
  'Profile Link': '/author/Thomas-A-Edison',
  'Tags': ['edison', 'failure', 'inspirational', 'paraphrased']},
 {'Quote': "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
  'Author': 'Eleanor Roosevelt',
  'Profile Link': '/author/Eleanor-Roosevelt',
  'Tags': ['misattributed-eleanor-roosevelt']},
 {'Quote': 'A day without sunshine is like, you know, night.',
  'Author': 'Steve Martin',
  'Profile Link': '/author/Steve-Martin',
  'Tags': ['humor', 'obvious', 'simile']}]

## Step 6: Convert into Dataframe

In [54]:
# Creating a dataframe from the data
df=pd.DataFrame(Data, columns=['Quote', 'Author', 'Profile Link', 'Tags'])

In [55]:
df

,Quote,Author,Profile Link,Tags
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"[change, deep-thoughts, thinking, world]"
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"[abilities, choices]"
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"[inspirational, life, live, miracle, miracles]"
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"[aliteracy, books, classic, humor]"
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"[be-yourself, inspirational]"
5,Try not to become a man of success. Rather bec...,Albert Einstein,/author/Albert-Einstein,"[adulthood, success, value]"
6,It is better to be hated for what you are than...,André Gide,/author/Andre-Gide,"[life, love]"
7,"I have not failed. I've just found 10,000 ways...",Thomas A. Edison,/author/Thomas-A-Edison,"[edison, failure, inspirational, paraphrased]"
8,A woman is like a tea bag; you never know how ...,Eleanor Roosevelt,/author/Eleanor-Roosevelt,[misattributed-eleanor-roosevelt]
9,"A day without sunshine is like, you know, night.",Steve Martin,/author/Steve-Martin,"[humor, obvious, simile]"

This code is for the first page of the website. You can use a loop to iterate through all the pages and extract the data.

## Step 8: Scrapping Multiple Pages

In [57]:
# Now we will extract the data from multiple pages of the website
# this library is used to show the progress of the loop
from tqdm import tqdm
Multiple_Pages = []
for page in tqdm(range(1, 11)):
    link = ('http://quotes.toscrape.com/page/' + str(page))
    res = requests.get(link)
    soup = BeautifulSoup(res.text, 'html.parser')

    for sp in soup.find_all('div', class_='quote'):
        quote = sp.find('span', class_='text').text[1:-1]
        authors = sp.find('small', class_='author').text
        details = sp.find('a').get('href')
        tags = []

        for tag in sp.find_all('a', class_='tag'):
            tags.append(tag.text)

        # Joining the tags in a single string   
        tags = ','.join(tags)
        Multiple_Pages.append([quote, authors, details, tags])

100%|██████████| 10/10 [00:08<00:00,  1.23it/s]

In [ ]:
Multiple_Pages_df = pd.DataFrame(data=Multiple_Pages)
Multiple_Pages_df = Multiple_Pages_df.rename(
    columns={0: 'Quote', 1: 'Author', 2: 'Author_id', 3: 'Tags'})
Multiple_Pages_df['Author_Link'] = 'http://quotes.toscrape.com/' + \
    Multiple_Pages_df['Author_id']
Multiple_Pages_df.head()

,Quote,Author,Author_id,Tags,Author_Link
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world",http://quotes.toscrape.com//author/Albert-Eins...
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices",http://quotes.toscrape.com//author/J-K-Rowling
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles",http://quotes.toscrape.com//author/Albert-Eins...
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor",http://quotes.toscrape.com//author/Jane-Austen
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational",http://quotes.toscrape.com//author/Marilyn-Monroe

## Step 7: Save to CSV

In [59]:
# Saving the data in an excel file
with pd.ExcelWriter('Quotes.xlsx') as writer:
    Multiple_Pages_df.to_excel(writer, sheet_name='Quotes', index=False)